import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://demo.ff2024.s3-website.eu-west-3.amazonaws.com/');
  await page.getByLabel('User').fill('admin');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('trazit');
  await page.getByRole('button', { name: 'Access' }).click();
  await page.goto('http://demo.ff2024.s3-website.eu-west-3.amazonaws.com/dashboard');
  await page.getByRole('heading', { name: 'Welcome to the Trazit' }).click();
  await page.getByRole('menuitem', { name: 'Intruments Control' }).locator('span').click();
  await page.goto('http://demo.ff2024.s3-website.eu-west-3.amazonaws.com/dashboard/procedures?procName=instruments&viewName=PlatformInstruments&filterName=');
  await page.getByTitle('Turn online').getByRole('img').click();
  await page.getByTitle('Turn online').getByRole('img').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.getByTitle('Turn online').getByRole('img').click();
  await page.getByLabel('* Model').click();
  await page.getByLabel('* New Instrument Name').click();
  await page.getByLabel('* New Instrument Name').fill('testingg');
  await page.getByLabel('* Family').click();
  await page.getByLabel('* Model').click();
  await page.getByLabel('* Model').fill('1');
  await page.getByLabel('* Supplier').click();
  await page.getByLabel('* Supplier').click();
  await page.getByLabel('* Supplier').click();
  await page.getByLabel('* Serial Number').fill('1');
  await page.getByLabel('* ManufacturerName').click();
  await page.getByLabel('* Serial Number').click();
  await page.getByLabel('* ManufacturerName').click();
  await page.getByRole('option', { name: 'Mettler Toledo' }).click();
  await page.getByLabel('* ManufacturerName').click();
  await page.getByRole('option', { name: 'Perkin Elmer' }).click();
  await page.getByRole('option', { name: 'admin', exact: true }).click();
  await page.getByLabel('Responsible Backup').click();
  await page.getByRole('option', { name: 'admin', exact: true }).click();
  await page.getByLabel('Purchase Date').fill('2024-09-01');
  await page.getByTitle('Turn online').getByRole('img').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.getByTitle('Turn off-line').getByRole('img').click();
  await page.getByRole('textbox', { name: 'Justification Phrase' }).fill('testing');
});