import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://demo.ff2024.s3-website.eu-west-3.amazonaws.com/dashboard/procedures?procName=instruments&viewName=PlatformInstruments&filterName=');
  await page.goto('http://demo.ff2024.s3-website.eu-west-3.amazonaws.com/');
  await page.getByLabel('User').fill('admin');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('trazit');
  await page.getByLabel('Password').press('Enter');
  await page.goto('http://demo.ff2024.s3-website.eu-west-3.amazonaws.com/dashboard');
  await page.goto('http://demo.ff2024.s3-website.eu-west-3.amazonaws.com/dashboard/procedures?procName=instruments&viewName=PlatformInstruments&filterName=');
  await page.getByLabel('create_new_folder').click();
  await page.getByLabel('* New Instrument Name').click();
  await page.getByLabel('* New Instrument Name').fill('pruebaa');
  await page.getByLabel('* New Instrument Name').click();
  await page.getByLabel('* New Instrument Name').fill('prueba{}');
  await page.getByLabel('* New Instrument Name').press('ArrowLeft');
  await page.getByLabel('* New Instrument Name').press('CapsLock');
  await page.getByLabel('* New Instrument Name').fill('prueba{TZ_DATE}');
  await page.getByLabel('* New Instrument Name').press('CapsLock');
  await page.getByLabel('* Family').click();
  await page.getByRole('option', { name: 'Viscosimetro' }).locator('span').click();
  await page.getByLabel('* Model').fill('1');
  await page.getByLabel('* Model').click();
  await page.getByLabel('* Supplier').click();
  await page.getByRole('option', { name: 'PB Instruments' }).click();
  await page.getByLabel('* Serial Number').fill('1');
  await page.getByLabel('* Serial Number').click();
  await page.getByLabel('* ManufacturerName').click();
  await page.getByLabel('Responsible', { exact: true }).click();
  await page.getByRole('option', { name: 'admin', exact: true }).click();
  await page.getByLabel('Responsible Backup').click();
  await page.getByRole('option', { name: 'admin', exact: true }).click();
  await page.getByLabel('Purchase Date').press('ArrowRight');
  await page.getByLabel('Purchase Date').fill('2024-09-01');
  await page.getByRole('button', { name: 'Accept' }).click();
});