export const newInstrumentSuccess={
    viewNameInModel: "PlatformInstruments",
    viewNameOrTextToGet: "Active",
	formData:[	
		{"text1"label:"Serial", value:"456"},	
	]
	fldName:{label:"New", value:"Frontend Testing {TZ_DATE}"}, 
    fldFamily:{label:"Family", value:"HPLC"},
    fldModel:{label:"Model", value:"123"},
    fldSupplier:{label:"Supplier", value:"Leica Bio"},
    fldSerial:{label:"Serial", value:"456"},
    fldManufacturer:{label:"Manufacture", value:"Mettler Toledo"},
    fldResponsible:{label:"Responsible", value:"admin"},
    fldResponsibleBackup:{label:"Backup", value:"procsadmin"},
    fldPurchase:{label:"Purchase", value:"12032023"},
    fldInstallation:{label:"Installation", value:"12042023"},
    textInNotif1: "Instrument",
    textInNotif2: "created",
    textInNotif3: "success",
}

export const newInstrumentAlreadyExists={
    viewNameInModel: "PlatformInstruments",
    viewNameOrTextToGet: "Active",
	fldName:{label:"New", value:"Frontend Testing 101"},
    fldFamily:{label:"Family", value:"HPLC"},
    fldModel:{label:"Model", value:"123"},
    fldSupplier:{label:"Supplier", value:"Leica Bio"},
    fldSerial:{label:"Serial", value:"456"},
    fldManufacturer:{label:"Manufacture", value:"Mettler Toledo"},
    fldResponsible:{label:"Responsible", value:"admin"},
    fldResponsibleBackup:{label:"Backup", value:"procsadmin"},
    fldPurchase:{label:"Purchase", value:"12032023"},
    fldInstallation:{label:"Installation", value:"12042023"},
    textInNotif1: "Instrument",
    textInNotif2: "already",
    textInNotif3: "exists",
}
export const newInstrumentRegression={
    viewNameInModel: "PlatformInstruments",
    viewNameOrTextToGet: "Active",
	fldName:{label:"New", value:"Frontend Testing {TZ_DATE}"}, 
    fldFamily:{label:"Family", value:"HPLC"},
    fldModel:{label:"Model", value:"123"},
    fldSupplier:{label:"Supplier", value:"Leica Bio"},
    fldSerial:{label:"Serial", value:"456"},
    fldManufacturer:{label:"Manufacture", value:"Mettler Toledo"},
    fldResponsible:{label:"Responsible", value:"admin"},
    fldResponsibleBackup:{label:"Backup", value:"procsadmin"},
    fldPurchase:{label:"Purchase", value:"12032023"},
    fldInstallation:{label:"Installation", value:"12042023"},
    textInNotif1: "Instrument",
    textInNotif2: "created",
    textInNotif3: "success",
}
